### ISSUE TITLE
Single day plot functions adds "k" to unit, if larger than a certain value.

### ISSUE THREAD

**Issue by FranzOldopp** [FZJ-IEK3-VSA/HiSim#163]
https://github.com/FZJ-IEK3-VSA/HiSim/blob/5d7b2ce4b4f1cb015ea2e8c15111b3b37ae1564a/hisim/postprocessing/chart_singleday.py#LL145C1-L147C44

The auto conversion of the unit should be removed, since it adds a "k" for example to"kW" showing "kkW" in the created plots.

**Comment by k-rieck** [comment]
Hey Franz, ist das Problem noch da bzw. hast du ein Beispiel? Weil ich bis jetzt kein Beispiel gefunden habe, wosowas wie kkW vorkam. Danke! @FranzOldopp
