### ISSUE TITLE
Heatpumps with Heatsource "Ground" 

### ISSUE THREAD

**Issue by H0ooo** [FZJ-IEK3-VSA/HiSim#170]
Every Heatpump from the database (input->smart devices) with Heatsource "Ground" do not work with the examples an the generic heatpump model.

**Comment by noah80** [comment]
Thanks for reporting the issues.

Could you give a few more details to enable us to reproduce the problem?

**Comment by H0ooo** [comment]
For example if i use the example "basic_household_with_new_hp_hds_hws_and_pv.py". The default heatpump (heatpump model "generic_heat_pump_for_house_with_hdy.py") in the model is a air heatpump (see picture):

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/22bb46e8-8cae-41a3-94a8-431578cf575a)

If i change the heatpump in the default function of the heatpump model to a heatpump with "Ground" as source (a heatpump from the list in the input folder "smart devices) the followig error is detected:

Picture of the "new" default function with the Ground heatpump of NIBE (listed in "smart_devices.json"):

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/43d7627f-854e-4864-82a8-ec7d38c9392b)


Error message of the example "basic_household_with_new_hp_hds_hws_and_pv.py" only by changing the heatpump from air to ground:

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/7679e10b-c50d-4aba-83a9-ca1e0558ffbb)

The problem appears also in the exmample "basic_household.py" if i change the default Air heatpump to a ground heatpump in the "generic_heatpump" model.


Thanks for your quick response!

**Comment by H0ooo** [comment]
Hi, i have another issue with the heatpumps, espacially the generic heatpump for houses with hds.
When simulating the example "basic_household_with_new_hp_hds_hws_and_pv.py" about one year (nothing else changed in the example) the heating power, temperature ouput and the electricity output of the heatpump is always the same. So the COP is also a constant value, although it depends on the outside air temperature and should change over the time. I attached the outside air temperature, the heating power of the heatpump and the COP.

![Heating_HeatPump](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/34c1d64b-067f-4691-a75a-a8c7b9d9d595)

![COP_Heatpump](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/a4caeec8-9266-4191-8459-a404e73725d6)

![TemperatureOutside_Weather](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/efa90dc0-375b-4396-8bd3-d0d9e26fcab2)

**Comment by k-rieck** [comment]
Hi, thanks for your comments! We removed the example "basic_household_with_new_hp_hds_hws_and_pv.py" because it is outdated. Please try another example and let us know if any problems occur. Thank you
