### ISSUE TITLE
Error when simulating with "loadprofilegenerator_utsp_connector"

### ISSUE THREAD

**Issue by Hoppe-J** [FZJ-IEK3-VSA/HiSim#261]
Hi,
when simulating with the loadprofilegenerator_utsp_connector the following error occurs:

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/dd4e62ef-bb14-40aa-9a73-ee56332a698f)

Maybe, it is because the StrGuid in the JsonReferences in the TravelRouteSets were changed in the utps client, but not updated in the lib of hisim:
In HiSim:

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/00db9cb7-082c-417a-9cff-6766a24483cb)

In the utps client (from Github):

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/d13f8715-ece9-4e14-9705-d72da614d7f7)

**Comment by Hoppe-J** [comment]
I update the utpsclient package in hisim, so the class "TravelRouteSets" were correct, but the "lpg_helper.py" file were already false. I copied it from github to the hisim package folder of the utpsclient. Now it works. Maybe there has to be a "new" update, which replace the utpsclient files.

**Comment by noah80** [comment]
We are currently in the process of revising the UTSP client and connector. Should hopefully be done next week.

**Comment by noah80** [comment]
Solved by improving the utsp connector to have an offline mode.
