### ISSUE TITLE
Module Not FoundError: No module named 'obsolete'

### ISSUE THREAD

**Issue by Mousa-Zerai** [FZJ-IEK3-VSA/HiSim#313]
(newhisim) C:\HiSim\hisim>python .\hisim_main.py ..\examples\basic_household.py basic_household_explicit
Traceback (most recent call last):
  File "C:\HiSim\hisim\hisim_main.py", line 12, in <module>
    import hisim.simulator as sim
  File "C:\HiSim\hisim\simulator.py", line 15, in <module>
    from hisim.postprocessing import postprocessing_main as pp
  File "C:\HiSim\hisim\postprocessing\postprocessing_main.py", line 13, in <module>
    from hisim.components import building
  File "C:\HiSim\hisim\components\building.py", line 60, in <module>
    from obsolete import loadprofilegenerator_connector
**ModuleNotFoundError: No module named 'obsolete'**

**Comment by k-rieck** [comment]
Hello, thanks for your comment.
We removed the obsolete loadprofilegenerator_connector import. Normally this error should not occur anymore

**Comment by Mousa-Zerai** [comment]
Hi there,

Thanks for removing this error. How does it work now? Do i need to remove
HiSim from my computer and reinstall it again and it should work fine?

I also have another question: To change the occupancy type/number of people
in the house, I have run some simulations in Loadprofilegenerator with
different occupancy types. Do i just change the input files in the
following path hisim/inputs/loadprofiles, or is there a different way of
doing it ?


I look forward to hearing from you very soon.


Best regards,
Mousa Zerai
