### ISSUE TITLE
No module named error

### ISSUE THREAD

**Issue by MFaisalZaki** [FZJ-IEK3-VSA/HiSim#358]
Hello, 

I have tried the sample example provided in the readme, and I do get this error:
```
  File "hisim/venv/lib/python3.12/site-packages/hisim/component.py", line 21, in <module>
    from hisim.postprocessing.kpi_computation.kpi_structure import KpiEntry
ModuleNotFoundError: No module named 'hisim.postprocessing.kpi_computation'
```

**Comment by k-rieck** [comment]
Many thanks for your comment.
This looks like something went wrong with the installation of your HiSim package. Did you install your HiSim repository like described in the readme?

**Comment by MFaisalZaki** [comment]
Hello,

Sorry for responding late. I have followed the installation instructions using Conda and it works fine. My problem was I was using pip install git+Hisim-url.
