### ISSUE TITLE
Error while running examples after updates

### ISSUE THREAD

**Issue by sdickler** [FZJ-IEK3-VSA/HiSim#71]
Log message:

(hisimvenv) C:\...\HiSim\examples>python ../hisim/hisim_main.py examples first_example
LogPrio.Information:calling first_example from examples
LogPrio.Information:#################################
LogPrio.Information:starting simulation of examples first_example
LogPrio.Information:Start @ 15-Aug-2022 16:33:13
LogPrio.Profile:examples first_exampleStart @ 15-Aug-2022 16:33:13
LogPrio.Information:#################################
LogPrio.Profile:Executing hisim.simulator.__init__ took 0.06 seconds
LogPrio.Information:Starting first example:
Traceback (most recent call last):
  File "C:\...\HiSim\hisim\hisim_main.py", line 74, in <module>
    main(filename, function_name)
  File "C:\...\HiSim\hisim\hisim_main.py", line 53, in main
    model_init_method(my_sim, my_simulation_parameters)
  File "C:\...\HiSim\examples\examples.py", line 26, in first_example
    my_sim.set_simulation_parameters(my_simulation_parameters)
AttributeError: 'Simulator' object has no attribute 'set_simulation_parameters'

**Comment by noah80** [comment]
pip install issue. Solved.
