### ISSUE TITLE
Inconsistent file path

### ISSUE THREAD

**Issue by Mousa-Zerai** [FZJ-IEK3-VSA/HiSim#85]
bug:  data path is inconsistent with the developed code of reading files

fix: Moving inputs/weather/NSRDB to inputs\weather\test-reference-years_2015-2045_15-locations\NSRDB

**Comment by k-rieck** [comment]
Hello, 
thanks for your comment. I am sorry that the answer took so long. Can you give us some more information about the issue if it is still existing? Then we will have a look at it.
Thanks

**Comment by Mousa-Zerai** [comment]
Hello,

This issue has been resolved—many thanks for the follow-up.

Regards,
Mousa Zerai
